### PR TITLE
Update erlang to 24.0.6

### PR DESCRIPTION
**Pull request by eldano**

### CODE REVIEW

**Review by grzuy — APPROVED** [review]
:100:

**Comment by grzuy** [comment]
Just realized this introduced a new warning that appears when running `mix test`.

```
$ mix test
Excluding tags: [:pending]

...............................................warning: a term is constructed, but never used
  test/elixir_console_web/features/console_test.exs

.............................................

Finished in 3.1 seconds
4 features, 89 tests, 0 failures, 1 excluded

Randomized with seed 790915
```

**Comment by eldano** [comment]
Yeah I see it too but it doesn't seem to be an error in our code and it has to do with Wallaby.

**Comment by grzuy** [comment]
Yeah... unfortunately the warning message also doesn't print a line number or a stracktrace to better understand where that is coming from :-/

**Comment by eldano** [comment]
Relevant: https://elixirforum.com/t/erlang-otp-24-0-released/39630/63

**Pull request merged**
