### PR TITLE
Attempt to improve semantics of event name

### PR DESCRIPTION
**Pull request by grzuy**
Motivation coming from the fact I was a bit confused by an event called "suggest" was being used to handle both the suggestions and the expression history.

### CODE REVIEW

**Review by eldano — COMMENTED** [review]
I've been thinking if it's ok to have `phx-keydown` attribute on this element that already has a `phx-hook` or if it would be better to handle everything in the hook?
That way we would talk to the server only when certain keys were pressed and we could have separate events for autocomplete and history. We also wouldn't need a default clause.
The negative part is that hooks make us write javascript which would be nice to avoid but I prefer this over sending a lot of unnecessary events through the socket.
In any case, we could merge this PR and handle that later. Thoughts?

**Comment by grzuy** [comment]
> I've been thinking if it's ok to have `phx-keydown` attribute on this element that already has a `phx-hook` or if it would be better to handle everything in the hook?
> That way we would talk to the server only when certain keys were pressed and we could have separate events for autocomplete and history. We also wouldn't need a default clause.
> The negative part is that hooks make us write javascript which would be nice to avoid but I prefer this over sending a lot of unnecessary events through the socket.

Yes, good call.

Just looking at docs, could this `phx-key` work to scope the sent events? https://hexdocs.pm/phoenix_live_view/0.16.3/bindings.html#key-events.

> In any case, we could merge this PR and handle that later. Thoughts?

Yes.
We can merge as is and quickly gain in readability with this one then consider the best approach for filtering keydowns. :+1:

**Comment by eldano** [comment]
> Just looking at docs, could this phx-key work to scope the sent events?

I don't think we can define 3 different keys to scope the events, if we could that would be a better approach.

**Review by eldano — APPROVED** [review]

**Comment by grzuy** [comment]
> > Just looking at docs, could this phx-key work to scope the sent events?
> 
> I don't think we can define 3 different keys to scope the events, if we could that would be a better approach.

Mmm, gotcha. I'll dig a bit to see what's actually possible and not.

**Pull request merged**
