### PR TITLE
Upgrade elixir to v1.12

### PR DESCRIPTION
**Pull request by grzuy**
- [x] Fix any compilation warnings coming from this app
- [x] Fix any failing tests
- [x] Check changelog [entry](https://github.com/elixir-lang/elixir/blob/v1.12/CHANGELOG.md#changelog-for-elixir-v112)

### CODE REVIEW

**Comment by grzuy** [comment]
Test failing because elixir no longer sorts binding, intentional: https://github.com/elixir-lang/elixir/commit/f0b227d4010d223075fc1880329fee260b985a4d.

I need to update tests so that they don't depend on order or apply sorting in the app if that affects the way they are displayed in the sidebar.

**Comment by eldano** [comment]
Elixir 1.12 added support for [stepped ranges](https://github.com/elixir-lang/elixir/blob/v1.12/CHANGELOG.md#stepped-ranges), we need to add support for them.

**Comment by grzuy** [comment]
> Elixir 1.12 added support for [stepped ranges](https://github.com/elixir-lang/elixir/blob/v1.12/CHANGELOG.md#stepped-ranges), we need to add support for them.

Oh right, I assumed they were going to work out of the box, but you're right. They're not working.
Thanks!

**Comment by grzuy** [comment]
Allowed.

Still need to figure out how to make the docs for stepped ranges appear given they are a new type of binary operator.

**Comment by eldano** [comment]
> Still need to figure out how to make the docs for stepped ranges appear given they are a new type of binary operator.

Nice! Yeah more like a ternary operator. We need to think where the user should click to get the documentation because the operator is splitted in this case. I don't think we'll find a simple solution so maybe we could leave that outside of the scope of this PR. Wdyt?

**Comment by grzuy** [comment]
> > Still need to figure out how to make the docs for stepped ranges appear given they are a new type of binary operator.
> 
> Nice! Yeah more like a ternary operator. We need to think where the user should click to get the documentation because the operator is splitted in this case. I don't think we'll find a simple solution so maybe we could leave that outside of the scope of this PR. Wdyt?

Sounds like a good idea to me :+1:

**Review by eldano — APPROVED** [review]

**Pull request merged**
