### PR TITLE
Update to elixir v1.11

### PR DESCRIPTION
**Pull request by grzuy**
- [x] Fix `mix compile` warnings coming from this webapp's code
- [x] Fix `mix test` warnings coming from this webapp's code
- [x] Check Elixir v1.11 [changelog](https://github.com/elixir-lang/elixir/blob/v1.11/CHANGELOG.md#changelog-for-elixir-v111) for possible needed changes

### CODE REVIEW

**Comment by grzuy** [comment]
This has a lot of warnings coming from phoenix that are fixed on phoenix v1.5.

So it might be preferable to first get https://github.com/wyeworks/elixir_console/pull/116 in before this one.

**Comment by grzuy** [comment]
Now built on top of `phoenix-1-5` branch.
Also updated PR base branch.

**Comment by grzuy** [comment]
> I think we should whitelist the new Kernel functions added in Elixir 1.11 as part of this PR

I checked yesterday for new `Kernel` functions and couldn't find any. I found only 3 new macros.
Do you think there's any change needed in relation with those added?

**Comment by eldano** [comment]
I don't get autocompletes for is_exception/1, is_exception/2 and is_struct/2, and they fail when executing those, but in iex they do suggest autocompletions and I can execute them without issues

**Review by eldano — APPROVED** [review]
Looks good! For some reason, sourcelevel got stuck

**Comment by grzuy** [comment]
> I don't get autocompletes for is_exception/1, is_exception/2 and is_struct/2, and they fail when executing those, but in iex they do suggest autocompletions and I can execute them without issues

Right, good call.

**Pull request merged**
