### PR TITLE
Remove unused auto-generated errors helpers code

### PR DESCRIPTION
**Pull request by grzuy**
Addresses https://github.com/wyeworks/elixir_console/pull/126#pullrequestreview-756769321.

### CODE REVIEW

**Review by eldano — COMMENTED** [review]
I think you also need to unlock the dependency so it gets removed from mix.lock

**Comment by grzuy** [comment]
> I think you also need to unlock the dependency so it gets removed from mix.lock

Hehe, used to `bundler` automatically cleaning these up :laughing: 

Thanks!

Would be good to have the CI fail if we have these deps dangling...

**Comment by grzuy** [comment]
> 
> Would be good to have the CI fail if we have these deps dangling...

Done.

**Comment by grzuy** [comment]
Made separate commits to show the new CI step working correctly. Will squash when merging.

**Review by eldano — APPROVED** [review]
Looks good!
Maybe when you squash you can separate the part that adds the CI check and the part that removes the gettext dependency

**Pull request merged**
